### ISSUE TITLE
change cloud variable server

### ISSUE THREAD

**Issue by dumorando** [nmsderp/FreeScreenShareAPI#1]
[to infinity-server. ](https://github.com/thepython555/Infinity-Server)

way less limited then turbowarps cloud variable server

**Comment by nmsderp** [comment]
Nice! But I can't find the server url that this is hosted on.

**Comment by nmsderp** [comment]
It's fine if there is no open url, cuz i can host it on glitch.

**Comment by dumorando** [comment]
oh sorry its infinity-server.onrender.com

**Comment by nmsderp** [comment]
thanks!
